application: swimparser
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: static/stylesheets

- url: /log
  script: swim.app
  login: required
  
- url: /help
  static_dir: static/help

- url: /xml
  static_dir: xml
  
- url: /.*
  script: swim.app
  
libraries:
- name: jinja2
  version: latest