
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xc1\x10\xc7\x10\x99\xc1r\x02\xf2\xc7\xfa\t\xefz4\x89'
    
_lr_action_items = {'ZONE':([1,5,7,8,9,10,11,15,16,21,],[-9,-10,-13,-16,-14,18,-12,-17,-15,-11,]),'MULT':([5,],[14,]),'NUMBER':([0,1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,],[5,-9,-5,5,-10,-6,-13,-16,-14,-9,-12,-3,-4,21,-17,-15,-9,-18,-19,5,-11,-8,26,-22,5,-21,-7,29,-20,]),'R_BRACKET':([1,2,5,6,7,8,9,10,11,12,13,15,16,17,18,19,21,22,24,25,26,27,29,],[-9,-5,-10,-6,-13,-16,-14,-9,-12,-3,-4,-17,-15,-9,-18,-19,-11,-8,-22,27,-21,-7,-20,]),'STROKE':([1,5,21,],[7,-10,-11,]),'L_BRACKET':([14,],[20,]),'AT':([1,5,7,8,9,10,11,15,16,17,18,19,21,],[-9,-10,-13,-16,-14,-9,-12,-17,-15,23,-18,-19,-11,]),'DRILL':([1,5,7,21,],[9,-10,16,-11,]),'COLON':([26,],[28,]),'KICK':([1,5,7,21,],[8,-10,15,-11,]),'$end':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,21,22,24,26,27,29,],[-1,-9,-5,0,-2,-10,-6,-13,-16,-14,-9,-12,-3,-4,-17,-15,-9,-18,-19,-11,-8,-22,-21,-7,-20,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'count':([0,4,20,25,],[1,1,1,1,]),'set':([0,4,20,25,],[2,12,2,12,]),'zone':([10,],[17,]),'workout':([0,],[3,]),'set_list':([0,20,],[4,25,]),'interval':([17,],[22,]),'skill':([1,],[10,]),'multi_set':([0,4,20,25,],[6,13,6,13,]),'empty':([1,10,17,],[11,19,24,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> workout","S'",1,None,None,None),
  ('workout -> <empty>','workout',0,'p_workout_or_empty','swim_parser.py',25),
  ('workout -> set_list','workout',1,'p_workout_or_empty','swim_parser.py',26),
  ('set_list -> set_list set','set_list',2,'p_workout','swim_parser.py',35),
  ('set_list -> set_list multi_set','set_list',2,'p_workout','swim_parser.py',36),
  ('set_list -> set','set_list',1,'p_set_list','swim_parser.py',43),
  ('set_list -> multi_set','set_list',1,'p_set_list','swim_parser.py',44),
  ('multi_set -> NUMBER MULT L_BRACKET set_list R_BRACKET','multi_set',5,'p_super_set','swim_parser.py',50),
  ('set -> count skill zone interval','set',4,'p_set','swim_parser.py',57),
  ('empty -> <empty>','empty',0,'p_empty','swim_parser.py',65),
  ('count -> NUMBER','count',1,'p_count','swim_parser.py',70),
  ('count -> NUMBER MULT NUMBER','count',3,'p_count','swim_parser.py',71),
  ('skill -> empty','skill',1,'p_skill_stroke','swim_parser.py',82),
  ('skill -> STROKE','skill',1,'p_skill_stroke','swim_parser.py',83),
  ('skill -> DRILL','skill',1,'p_skill_drill','swim_parser.py',92),
  ('skill -> STROKE DRILL','skill',2,'p_skill_drill','swim_parser.py',93),
  ('skill -> KICK','skill',1,'p_skill_kick','swim_parser.py',102),
  ('skill -> STROKE KICK','skill',2,'p_skill_kick','swim_parser.py',103),
  ('zone -> ZONE','zone',1,'p_zone','swim_parser.py',112),
  ('zone -> empty','zone',1,'p_zone','swim_parser.py',113),
  ('interval -> AT NUMBER COLON NUMBER','interval',4,'p_interval','swim_parser.py',122),
  ('interval -> AT NUMBER','interval',2,'p_interval','swim_parser.py',123),
  ('interval -> empty','interval',1,'p_interval','swim_parser.py',124),
]
